### ISSUE TITLE
Custom covariate help

### ISSUE THREAD

**Issue by Sigfried** [Sigfried/HivDescriptive#3]
Help with creating and analyzing custom covariates:

 1. length of observation
 2. top 10 drug exposures in cohort
 3. visit density

Which custom covariate technique should we be using? (from cohort attributes or the more advanced technique?)

https://github.com/ohdsistudynurture/OhdsiStudyNurtureCommittee/issues/1

**Comment by chandryou** [comment]
@Sigfried 

1. Could you specify the start and the end for the length of observation?
2. Do you have any time span for the drug exposure in mind? 
3. Again, what is the time span for visit density? 

For calculating the length of observation, yes we need to develop custom covariate technique, which is not tough! You can see how you can do [here](https://raw.githubusercontent.com/OHDSI/FeatureExtraction/master/inst/doc/CreatingCustomCovariateBuilders.pdf). Of course, we can make it for you.

**Comment by Sigfried** [comment]
Hi Chan,
What I'm concerned about at the moment is just being able to generate and use a custom covariate. I'll talk to Vojtech about the details, but whatever they are, I should be able to write the SQL or R code or whatever is needed. Maybe you need to know more specifics in order to determine whether custom covariates are necessary and whether custom covariates from cohort attributes are sufficient. If that's the case, I'd like to learn how you would make that decision.

And, yes, I've been starting from the length of observation example you pointed to. You can see where it fits in my code [here](https://github.com/Sigfried/HivDescriptive/blob/custom-covar/R/CreateCovariates.R#L39) and [here](https://github.com/Sigfried/HivDescriptive/blob/custom-covar/inst/sql/sql_server/LengthOfObsCohortAttr.sql).

Thanks!

**Comment by Sigfried** [comment]
I've tracked down the problem I'm having with the code above right now to [line 70](https://github.com/Sigfried/HivDescriptive/blob/custom-covar/R/CreateCovariates.R#L70): 

    aggcovariates <- aggregateCovariates(covariates)

Length of observation (covariateId == 1) shows up in covariates$covariates (actually I see two identical rows for each patient), but not in aggcovariates$covariates.

I could aggregate it myself, but I don't want to interfere with the objects being created by FeatureExtraction functions. I guess my next step will be stepping through aggregateCovariates() in the debugger.

**Comment by Sigfried** [comment]
Ok, I think I figured it out and maybe it's a bug or at least a question for Martijn.

Length of observation is numeric, not binary, but the values show up in covariateData$covariates, not covariateData$covariatesContinuous.

**Comment by Sigfried** [comment]
I figured out (and commented in that FeatureExtraction issue) that FeatureExtraction doesn't yet support aggregating covariates from cohort attributes. So I guess that answers my question about that, and I should move on to the other method of making custom covariates. (Which I think is what Chan referenced above.)

**Comment by Sigfried** [comment]
Martijn solved the problem I was having with aggregating custom covariates: https://github.com/OHDSI/FeatureExtraction/issues/79

Now I still don't know what's better, making them from cohort attributes or making them from a custom function, but it may not matter. I had already switched my code to the custom function and I'll stick with that for now.
