### ISSUE TITLE
minCellCount Policy

### ISSUE THREAD

**Issue by chandryou** [Sigfried/HivDescriptive#5]
I think minCellCount Policy should be applied, such as remove information cells with value less than 5.

**Comment by Sigfried** [comment]
I think you're right. Vojtech and I spoke about that, but we're leaving it as is until things are working a little better. Thanks for catching it!

**Comment by chandryou** [comment]
The function below might be helpful. 

```
enforceMinCellValue <- function(data, fieldName, minValues, silent = FALSE) {
  toCensor <- !is.na(data[, fieldName]) & data[, fieldName] < minValues & data[, fieldName] != 0
  if (!silent) {
    percent <- round(100 * sum(toCensor)/nrow(data), 1)
    ParallelLogger::logInfo("   censoring ",
                            sum(toCensor),
                            " values (",
                            percent,
                            "%) from ",
                            fieldName,
                            " because value below minimum")
  }
  if (length(minValues) == 1) {
    data[toCensor, fieldName] <- -minValues
  } else {
    data[toCensor, fieldName] <- -minValues[toCensor]
  }
  return(data)
}
```

**Comment by Sigfried** [comment]
Hi Chan. I just noticed this after already writing some code for it. I need to set my github alerts differently :(

Anyway, what I added is the filter line below:

    result <-
          acvs %>%
          filter(is.numeric(sumValue) & sumValue >= min_cell_count) %>%
          dplyr::left_join(acvref) %>%
          dplyr::left_join(aaref) %>%
          dplyr::group_by(analysisId) %>%
          dplyr::top_n(10, sumValue) %>% dplyr::arrange(analysisName, -sumValue)

**Comment by Sigfried** [comment]
I can go back and add your version, which looks like it would work whether the data is aggregated or not. Mine only works with aggregated. If you think I should, could you point me to an example where your `enforceMinCellValue` function is used? Thanks!

**Comment by chandryou** [comment]
I used `enforceMinCellValue` function in the export function [here](https://github.com/chandryou/TicagrelorVsClopidogrel/blob/master/R/Export.R)

**Comment by Sigfried** [comment]
Weird that this suddenly closed. I think I just pushed code onto the custom-covar branch that fixed it, but I'm not sure if it's in master yet. Will check at next release.
